---
title: 关于AdonisJs
permalink: about
category: 介绍
---
= 关于AdonisJs

toc::[]

AdonisJs是一个可以运行在所有主流操作系统上的Node.js MVC框架。 它提供了一个稳定的生态系统来编写一个服务器端web应用程序，这样您就可以专注于业务需求，而不是最终确定纠结要选择哪个包。

AdonisJs支持开发人员使用一致且富有表现力的API来构建一个完整的web应用程序或微API服务器。

== 起步
没有硬性条件要使用Adonisjs的，但是它对JavaScript, 异步编程和Node.js的基本理解是有帮助的。

另外，如果你是第一次使用AdonisJs，请确保要阅读link:installation[入门指南]

== 其他途径
这里还有一些其他途径去找到关于AdonisJs的信息。

1. link:https://forum.adonisjs.com[discourse forum, window="_blank"], 我们在这里讨论有关AdonisJs从修复错误到讨论新功能的所有内容。
2. 一些社区成员提供的link:/screencasts[截屏]。
2. Twitter
3. Github
4. 如果你喜欢这个项目，那么请在link:https://www.patreon.com/adonisframework[patreon, window="_blank"]上支持我们。

== 提供者(Providers)
AdonisJs是一个由多个服务提供商组成的模块化框架。 服务提供商是AdonisJs应用程序的基石。

从理论上讲，就像其它任何npm模块一样，可以用一些代码透明的构建AdonisJs应用程序。 例如, link:https://github.com/adonisjs/adonis-bodyparser[BodyParser] 解析HTTP请求体或者link:https://github.com/adonisjs/adonis-lucid[Lucid] 就是一个 SQL ORM.

== 常见问题
以下是常见问题列表，如果您认为列表中缺少常见问题。 请在link:https://github.com/adonisjs/docs[这里]创建一个问题。

[ol-spaced]
1. *AdonisJs与Express或Koa有什么不同？*
+
Express和Koa在路由库的基础上增加了一层中间件。 它对一些使用用例有好处，但是当项目增长（复杂）后会崩溃。
+
此外，因为你的项目有自己的标准和惯例，它变得更难雇人。 而AdonisJs遵循一套标准的约定，使其更容易让雇用的人在现有AdonisJs应用上上手工作。

2. *AdonisJs适用于单片应用程序吗？*
+
不，AdonisJs作为一个框架是多个软件包的组合，与您的应用程序的其他部分完美地集成。
+
该框架提供了一个强大的*依赖注入*层，所有官方和第三方包都利用该层来提供功能，而无需手动连接应用程序的每个部分。
