---
permalink: folder-structure
title: 文件夹结构
category: 起步
---
= 文件夹结构

toc::[]

在本指南中，我们将学习AdonisJs应用程序的结构以及它随着项目的发展如何优雅地扩展。

AdonisJs的理念始终是开始精益求精，并随需而变。 `adonis` 命令行带有一堆 *命令*，用于在需要时创建新的目录/文件。

TIP: 运行 `adonis --help` 来查看可用命令的列表

== 精简版结构
为了与AdonisJs合作，Slim结构是最基本的。

++++
<pre class="highlight line-numbers language-bash" data-line="2,5">
<code>.
├── ace
├── package.json
├── public
├── server.js
└── start
    ├── app.js
    ├── kernel.js
    └── routes.js
</code>
</pre>
++++

[options="header", cols="5,95"]
|====
| 文件/目录 | 描述
| ace | ace文件为您的项目特定命令引导命令行工具。运行 `node ace <命令名>` 执行该命令。
| package.json | 标准的Node.js包文件。
| public | 用于存放静态资源的公共文件夹，如 *Css，Javascript文件或图片*
| server.js | 该文件用于启动HTTP服务器。运行 `node server.js` 会启动.env文件中定义的端口上的HTTP服务器。 +
而在开发中，建议使用 `adonis serve --dev` 。
| start/app.js | 该文件用于注册提供者，命令和别名。您现在可以忽略此文件，特别是如果您不熟悉提供者。
| start/kernel.js | HTTP中间件注册在这个文件中。
| start/routes.js | 该文件用于定义HTTP路由。
|====

== 应用程序目录


`app` 目录存储您的所有应用程序代码,例如 *控制器*, *模型*, *命令*。

AdonisJs具有自动加载 `app` 目录的概念。这意味着您可以不需要具有相对路径的文件，而是需要具有命名空间的文件。例如：

[source, bash]
----
├── app
│   └── Services
│       └── User.js
----

通常你会需要上面的文件

[source, js]
----
const UserService = require('../app/Services/User')
----

使用自动加载时，可以导入为

[source, js]
----
const UserService = use('App/Services/User')
----

后面一种方法的好处是，*命名空间* 始终保持相同，您不必通过输入 `../` 来处理相对路径。

NOTE: 自动加载命名空间是在 link:https://github.com/adonisjs/adonis-slim-app/blob/master/package.json#L24[package.json, window="_blank"] 文件中定义的。您可以自由定义更多/唯一的命名空间。

== 视图
应用程序视图存储在 `resources/views` 目录中。每个视图文件以 `.edge` 结尾，并使用 link:http://edge.adonisjs.com/[edge, window="_blank"] 作为模板引擎。

您可以使用 `adonis make：view` 命令创建新的视图。

[source, bash]
----
adonis make:view welcome
----

对于嵌套视图运行以下命令
[source, bash]
----
adonis make:view users.list
----

== 静态资源
您应用中的 `public` 目录专门用于存储所有与前端相关的资源，如 *css*，*图片* 或 *javascript文件*。

您可以在不向URL添加 `/public` 的情况下访问这些文件。例如：

`public/style.css` 文件可以通过 link:http://127.0.0.1:3333/style.css[127.0.0.1:3333/style.css] 来访问

== 配置
为了让应用程序避免配置债务，AdonisJs为您提供专用目录 `/config` 来存储所有应用程序配置

建议在一个地方进行配置，并使用 *环境* 变量来管理秘钥。
link:configuration-and-env[了解更多]

== 测试
所有的应用程序测试都存储在 `test` 目录中。测试包默认不包含，因此您可以像 link:testing#_setup[这里]介绍的那样安装它。

软件包安装完成后，您可以运行以下命令。

[source, bash]
----
adonis make:test user
----

并按如下方式运行测试。

[source, bash]
----
adonis test
----

