---
permalink: configuration-and-env
title: 配置和环境变量
category: 起步
---
= Configuration and Env

toc::[]

在本指南中，我们将学习AdonisJs如何处理应用程序配置和环境变量。在本指南结束时，您将知道如何保持敏感信息的安全并避免配置债务(configuration debt)。

== 配置债务
在开始之前，让我们了解配置债务的概念。许多Node.js应用程序面临多个文件内部分散配置的问题。例如：

[ol-shrinked]
1. 使用路由文件定义中间件配置。
2. 在发送电子邮件的服务中定义电子邮件设置详细信息。

对于第一次使用代码库的新用户来说，找到所有配置变成了一场噩梦，并且他们一直在多个文件/目录间折腾。

为了避免这种行为，一个专用的目录 `config` 用于存放配置。

== 入门
在AdonisJs中，我们将所有配置存储在名为 `config` 的单独目录中。所有配置文件都在引导时加载，可以使用 * Config 提供者* 访问这些值。

假设我们想从 `config/app.js` 文件中读取 `appSecret` 。

[source, js]
----
const Config = use('Config')
const appSecret = Config.get('app.appSecret')
----

这些值通过定义 `文件名.键` 来获取。嵌套值可以使用点符号来获取。

.config/database.js
[source, js]
----
{
  mysql: {
    host: '127.0.0.1'
  }
}
----

现在，来访问它

[source, js]
----
Config.get('database.mysql.host')

// 或使用默认值
Config.get('database.mysql.host', '127.0.0.1')
----

您还可以更新密钥的内存配置值，如下所示。

[source, js]
----
Config.set('database.mysql.host', 'db.example.com')
----

== 环境变量
通常，您希望根据您的代码运行的环境来配置不同的配置。例如：在开发中使用 *沙盒秘钥* 调用第三方服务。

同样从安全角度来看，您绝不应该将您的生产凭证与所有在代码库上工作的开发人员共享。

相反，这些凭证作为环境变量存储在生产服务器上，并在本地开发应用程序时在 `.env` 文件中定义。

.env
[source, env]
----
APP_SECRET=F7op5n9vx1nAkno0DsNgZm5vjNXpOLIq
DB_HOST=127.0.0.1
DB_USER=root
----

现在你可以使用 `Env` 提供者来访问这些变量。

[source, js]
----
const Env = use('Env')
Env.get('APP_SECRET')
----

注意：`Env.get` 总是返回一个字符串。如果你想获得一个布尔值，你需要像这样校验它。 +
  `Env.get('...') === 'true'`

==== 不同的.env文件
有时您可能想要在不同的位置加载存储在服务器上的不同 `.env` 文件。同样可以做到，代码如下。

[source, bash]
----
ENV_PATH=/user/.env node server.js
----

==== 禁用.env文件
如果 `.env` 文件丢失，AdonisJs 默认会引发异常。但是，如下关闭异常。

[source, bash]
----
ENV_SILENT=true node server.js
----

==== 测试变量
如果您的应用程序以 `NODE_ENV=testing` 启动，AdonisJs会尝试从应用程序的根目录加载 `.env.testing` 文件。

该文件覆盖 `.env` 文件中的值，以便在运行测试时可以有稍微不同的配置。

.env.testing
[source, env]
----
DB_CONNECTION=sqlite
----
